### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by crumdidlyumshis** [Apollyonn/ElvUI_ExtraActionBars-4.3.4#1]
Not sure where else I could ask... I know I have asked Bunny about this before and he said it flat out could not be done. Is it really flat out not possible to backport this addon to 3.3.5 version? I just wanted to verify. :)

**Comment by Apollyonn** [comment]
This uses LibActionButton Library (LAB) and LAB is not compatible with clients below cataclysm and i think its impossible to be backported.

**Comment by crumdidlyumshis** [comment]
Dang! Well I do appreciate the feedback. I guess im stuck with Dominos for now. Dominos works, but it has some small glitches with ElvUI here and there.
